### ISSUE TITLE
Did the format of the TOO_FAST_RE message change?

### ISSUE THREAD

**Issue by tripleee** [Manishearth/ChatExchange#163]
I had a failure last night which seems to have been caused by quotes around the backoff message from the server. Did the format of the response change? Or should the regex match use `re.search()` instead of `re.match()`?

Ref. https://github.com/tripleee/sloshy/issues/8

**Comment by makyen** [comment]
No, the format of the response from SE has not changed. There are no quotes around the message received from SE's chat servers. The quotes you are seeing are added by the `logging` package.

The logging message which you show in your linked issue is 
> Attempt 1: denied: unknown reason 'You can perform this action again in 1 second.'

This is just a log output and does not indicate that the action wasn't retried. It does, however, indicate that there was a 5 second delay between logging that message and when the next attempt was made, rather than the 1 second which should have been the delay. A commit resolving the wrong delay in this circumstance was added in PR #159, which was merged on 2020-09-12. Please update your version of ChatExchange.
